//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 01:45:13 PM CST 
//


package com.yonyou.studio.mdp.inspector.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="accessStrategy" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="accesspower" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="accesspowergroup" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="calculation" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="classID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="dataType" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="dataTypeStyle" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="dbtype" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="defaultValue" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="displayName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="dynamic" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="dynamicTable" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fieldName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="fieldType" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fixedLength" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="forLocale" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="help" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="isActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isAuthorization" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isDefaultDimensionAttribute" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isDefaultMeasureAttribute" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isFeature" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isGlobalization" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isHide" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isKey" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isNullable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isReadOnly" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isShare" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="maxValue" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="minValue" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="notSerialize" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="precise" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="refModelName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="resid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="typeDisplayName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="typeName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="versionType" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="visibility" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "attribute")
public class Attribute {

    @XmlAttribute(name = "accessStrategy", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String accessStrategy;
    @XmlAttribute(name = "accesspower", required = true)
    protected boolean accesspower;
    @XmlAttribute(name = "accesspowergroup", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String accesspowergroup;
    @XmlAttribute(name = "calculation", required = true)
    protected boolean calculation;
    @XmlAttribute(name = "classID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String classID;
    @XmlAttribute(name = "dataType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String dataType;
    @XmlAttribute(name = "dataTypeStyle", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dataTypeStyle;
    @XmlAttribute(name = "dbtype", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dbtype;
    @XmlAttribute(name = "defaultValue", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String defaultValue;
    @XmlAttribute(name = "description", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String description;
    @XmlAttribute(name = "displayName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String displayName;
    @XmlAttribute(name = "dynamic", required = true)
    protected boolean dynamic;
    @XmlAttribute(name = "dynamicTable", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dynamicTable;
    @XmlAttribute(name = "fieldName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fieldName;
    @XmlAttribute(name = "fieldType", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fieldType;
    @XmlAttribute(name = "fixedLength", required = true)
    protected boolean fixedLength;
    @XmlAttribute(name = "forLocale", required = true)
    protected boolean forLocale;
    @XmlAttribute(name = "help", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String help;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "isActive", required = true)
    protected boolean isActive;
    @XmlAttribute(name = "isAuthorization", required = true)
    protected boolean isAuthorization;
    @XmlAttribute(name = "isDefaultDimensionAttribute", required = true)
    protected boolean isDefaultDimensionAttribute;
    @XmlAttribute(name = "isDefaultMeasureAttribute", required = true)
    protected boolean isDefaultMeasureAttribute;
    @XmlAttribute(name = "isFeature", required = true)
    protected boolean isFeature;
    @XmlAttribute(name = "isGlobalization", required = true)
    protected boolean isGlobalization;
    @XmlAttribute(name = "isHide", required = true)
    protected boolean isHide;
    @XmlAttribute(name = "isKey", required = true)
    protected boolean isKey;
    @XmlAttribute(name = "isNullable", required = true)
    protected boolean isNullable;
    @XmlAttribute(name = "isReadOnly", required = true)
    protected boolean isReadOnly;
    @XmlAttribute(name = "isShare", required = true)
    protected boolean isShare;
    @XmlAttribute(name = "length", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String length;
    @XmlAttribute(name = "maxValue", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String maxValue;
    @XmlAttribute(name = "minValue", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String minValue;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "notSerialize", required = true)
    protected boolean notSerialize;
    @XmlAttribute(name = "precise", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String precise;
    @XmlAttribute(name = "refModelName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String refModelName;
    @XmlAttribute(name = "resid", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String resid;
    @XmlAttribute(name = "sequence", required = true)
    protected BigInteger sequence;
    @XmlAttribute(name = "typeDisplayName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String typeDisplayName;
    @XmlAttribute(name = "typeName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String typeName;
    @XmlAttribute(name = "versionType", required = true)
    protected BigInteger versionType;
    @XmlAttribute(name = "visibility", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String visibility;

    /**
     * Gets the value of the accessStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessStrategy() {
        return accessStrategy;
    }

    /**
     * Sets the value of the accessStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessStrategy(String value) {
        this.accessStrategy = value;
    }

    /**
     * Gets the value of the accesspower property.
     * 
     */
    public boolean isAccesspower() {
        return accesspower;
    }

    /**
     * Sets the value of the accesspower property.
     * 
     */
    public void setAccesspower(boolean value) {
        this.accesspower = value;
    }

    /**
     * Gets the value of the accesspowergroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccesspowergroup() {
        return accesspowergroup;
    }

    /**
     * Sets the value of the accesspowergroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccesspowergroup(String value) {
        this.accesspowergroup = value;
    }

    /**
     * Gets the value of the calculation property.
     * 
     */
    public boolean isCalculation() {
        return calculation;
    }

    /**
     * Sets the value of the calculation property.
     * 
     */
    public void setCalculation(boolean value) {
        this.calculation = value;
    }

    /**
     * Gets the value of the classID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassID() {
        return classID;
    }

    /**
     * Sets the value of the classID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassID(String value) {
        this.classID = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the dataTypeStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataTypeStyle() {
        return dataTypeStyle;
    }

    /**
     * Sets the value of the dataTypeStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataTypeStyle(String value) {
        this.dataTypeStyle = value;
    }

    /**
     * Gets the value of the dbtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtype() {
        return dbtype;
    }

    /**
     * Sets the value of the dbtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtype(String value) {
        this.dbtype = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the dynamic property.
     * 
     */
    public boolean isDynamic() {
        return dynamic;
    }

    /**
     * Sets the value of the dynamic property.
     * 
     */
    public void setDynamic(boolean value) {
        this.dynamic = value;
    }

    /**
     * Gets the value of the dynamicTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDynamicTable() {
        return dynamicTable;
    }

    /**
     * Sets the value of the dynamicTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDynamicTable(String value) {
        this.dynamicTable = value;
    }

    /**
     * Gets the value of the fieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldName(String value) {
        this.fieldName = value;
    }

    /**
     * Gets the value of the fieldType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * Sets the value of the fieldType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldType(String value) {
        this.fieldType = value;
    }

    /**
     * Gets the value of the fixedLength property.
     * 
     */
    public boolean isFixedLength() {
        return fixedLength;
    }

    /**
     * Sets the value of the fixedLength property.
     * 
     */
    public void setFixedLength(boolean value) {
        this.fixedLength = value;
    }

    /**
     * Gets the value of the forLocale property.
     * 
     */
    public boolean isForLocale() {
        return forLocale;
    }

    /**
     * Sets the value of the forLocale property.
     * 
     */
    public void setForLocale(boolean value) {
        this.forLocale = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the isAuthorization property.
     * 
     */
    public boolean isIsAuthorization() {
        return isAuthorization;
    }

    /**
     * Sets the value of the isAuthorization property.
     * 
     */
    public void setIsAuthorization(boolean value) {
        this.isAuthorization = value;
    }

    /**
     * Gets the value of the isDefaultDimensionAttribute property.
     * 
     */
    public boolean isIsDefaultDimensionAttribute() {
        return isDefaultDimensionAttribute;
    }

    /**
     * Sets the value of the isDefaultDimensionAttribute property.
     * 
     */
    public void setIsDefaultDimensionAttribute(boolean value) {
        this.isDefaultDimensionAttribute = value;
    }

    /**
     * Gets the value of the isDefaultMeasureAttribute property.
     * 
     */
    public boolean isIsDefaultMeasureAttribute() {
        return isDefaultMeasureAttribute;
    }

    /**
     * Sets the value of the isDefaultMeasureAttribute property.
     * 
     */
    public void setIsDefaultMeasureAttribute(boolean value) {
        this.isDefaultMeasureAttribute = value;
    }

    /**
     * Gets the value of the isFeature property.
     * 
     */
    public boolean isIsFeature() {
        return isFeature;
    }

    /**
     * Sets the value of the isFeature property.
     * 
     */
    public void setIsFeature(boolean value) {
        this.isFeature = value;
    }

    /**
     * Gets the value of the isGlobalization property.
     * 
     */
    public boolean isIsGlobalization() {
        return isGlobalization;
    }

    /**
     * Sets the value of the isGlobalization property.
     * 
     */
    public void setIsGlobalization(boolean value) {
        this.isGlobalization = value;
    }

    /**
     * Gets the value of the isHide property.
     * 
     */
    public boolean isIsHide() {
        return isHide;
    }

    /**
     * Sets the value of the isHide property.
     * 
     */
    public void setIsHide(boolean value) {
        this.isHide = value;
    }

    /**
     * Gets the value of the isKey property.
     * 
     */
    public boolean isIsKey() {
        return isKey;
    }

    /**
     * Sets the value of the isKey property.
     * 
     */
    public void setIsKey(boolean value) {
        this.isKey = value;
    }

    /**
     * Gets the value of the isNullable property.
     * 
     */
    public boolean isIsNullable() {
        return isNullable;
    }

    /**
     * Sets the value of the isNullable property.
     * 
     */
    public void setIsNullable(boolean value) {
        this.isNullable = value;
    }

    /**
     * Gets the value of the isReadOnly property.
     * 
     */
    public boolean isIsReadOnly() {
        return isReadOnly;
    }

    /**
     * Sets the value of the isReadOnly property.
     * 
     */
    public void setIsReadOnly(boolean value) {
        this.isReadOnly = value;
    }

    /**
     * Gets the value of the isShare property.
     * 
     */
    public boolean isIsShare() {
        return isShare;
    }

    /**
     * Sets the value of the isShare property.
     * 
     */
    public void setIsShare(boolean value) {
        this.isShare = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxValue(String value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinValue(String value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the notSerialize property.
     * 
     */
    public boolean isNotSerialize() {
        return notSerialize;
    }

    /**
     * Sets the value of the notSerialize property.
     * 
     */
    public void setNotSerialize(boolean value) {
        this.notSerialize = value;
    }

    /**
     * Gets the value of the precise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecise() {
        return precise;
    }

    /**
     * Sets the value of the precise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecise(String value) {
        this.precise = value;
    }

    /**
     * Gets the value of the refModelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefModelName() {
        return refModelName;
    }

    /**
     * Sets the value of the refModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefModelName(String value) {
        this.refModelName = value;
    }

    /**
     * Gets the value of the resid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResid() {
        return resid;
    }

    /**
     * Sets the value of the resid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResid(String value) {
        this.resid = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the typeDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeDisplayName() {
        return typeDisplayName;
    }

    /**
     * Sets the value of the typeDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeDisplayName(String value) {
        this.typeDisplayName = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the versionType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionType() {
        return versionType;
    }

    /**
     * Sets the value of the versionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionType(BigInteger value) {
        this.versionType = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibility(String value) {
        this.visibility = value;
    }

}
