//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 01:45:13 PM CST 
//


package com.yonyou.studio.mdp.inspector.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="attrid" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="attrpath" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="attrpathid" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="busiitfattrid" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="busiitfid" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="cellid" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "busimap")
public class Busimap {

    @XmlAttribute(name = "attrid", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String attrid;
    @XmlAttribute(name = "attrpath", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String attrpath;
    @XmlAttribute(name = "attrpathid", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String attrpathid;
    @XmlAttribute(name = "busiitfattrid", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String busiitfattrid;
    @XmlAttribute(name = "busiitfid", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String busiitfid;
    @XmlAttribute(name = "cellid", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String cellid;

    /**
     * Gets the value of the attrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttrid() {
        return attrid;
    }

    /**
     * Sets the value of the attrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttrid(String value) {
        this.attrid = value;
    }

    /**
     * Gets the value of the attrpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttrpath() {
        return attrpath;
    }

    /**
     * Sets the value of the attrpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttrpath(String value) {
        this.attrpath = value;
    }

    /**
     * Gets the value of the attrpathid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttrpathid() {
        return attrpathid;
    }

    /**
     * Sets the value of the attrpathid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttrpathid(String value) {
        this.attrpathid = value;
    }

    /**
     * Gets the value of the busiitfattrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusiitfattrid() {
        return busiitfattrid;
    }

    /**
     * Sets the value of the busiitfattrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusiitfattrid(String value) {
        this.busiitfattrid = value;
    }

    /**
     * Gets the value of the busiitfid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusiitfid() {
        return busiitfid;
    }

    /**
     * Sets the value of the busiitfid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusiitfid(String value) {
        this.busiitfid = value;
    }

    /**
     * Gets the value of the cellid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellid() {
        return cellid;
    }

    /**
     * Sets the value of the cellid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellid(String value) {
        this.cellid = value;
    }

}
