//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 01:45:13 PM CST 
//


package com.yonyou.studio.mdp.inspector.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}celllist"/>
 *         &lt;element ref="{}connectlist"/>
 *         &lt;element ref="{}refdepends"/>
 *         &lt;element ref="{}refdependLoseIDs"/>
 *         &lt;element ref="{}cellRemoveLog"/>
 *         &lt;element ref="{}rulers"/>
 *       &lt;/sequence>
 *       &lt;attribute name="conRouterType" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="createTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="creator" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="displayName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="fromSourceBmf" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="gencodestyle" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="help" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="isbizmodel" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="mainEntity" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="modifier" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="modifyTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="namespace" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ownModule" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="preLoad" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="resModuleName" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="resid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="versionType" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "celllist",
    "connectlist",
    "refdepends",
    "refdependLoseIDs",
    "cellRemoveLog",
    "rulers"
})
@XmlRootElement(name = "component")
public class Component {

    @XmlElement(required = true)
    protected Celllist celllist;
    @XmlElement(required = true)
    protected Connectlist connectlist;
    @XmlElement(required = true)
    protected Refdepends refdepends;
    @XmlElement(required = true)
    protected RefdependLoseIDs refdependLoseIDs;
    @XmlElement(required = true)
    protected CellRemoveLog cellRemoveLog;
    @XmlElement(required = true)
    protected Rulers rulers;
    @XmlAttribute(name = "conRouterType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String conRouterType;
    @XmlAttribute(name = "createTime", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String createTime;
    @XmlAttribute(name = "creator", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String creator;
    @XmlAttribute(name = "description", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String description;
    @XmlAttribute(name = "displayName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String displayName;
    @XmlAttribute(name = "fromSourceBmf", required = true)
    protected boolean fromSourceBmf;
    @XmlAttribute(name = "gencodestyle", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String gencodestyle;
    @XmlAttribute(name = "help", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String help;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "isbizmodel", required = true)
    protected boolean isbizmodel;
    @XmlAttribute(name = "mainEntity", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String mainEntity;
    @XmlAttribute(name = "modifier", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String modifier;
    @XmlAttribute(name = "modifyTime", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String modifyTime;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "namespace", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String namespace;
    @XmlAttribute(name = "ownModule", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ownModule;
    @XmlAttribute(name = "preLoad", required = true)
    protected boolean preLoad;
    @XmlAttribute(name = "resModuleName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String resModuleName;
    @XmlAttribute(name = "resid", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String resid;
    @XmlAttribute(name = "version", required = true)
    protected BigInteger version;
    @XmlAttribute(name = "versionType", required = true)
    protected BigInteger versionType;

    /**
     * Gets the value of the celllist property.
     * 
     * @return
     *     possible object is
     *     {@link Celllist }
     *     
     */
    public Celllist getCelllist() {
        return celllist;
    }

    /**
     * Sets the value of the celllist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Celllist }
     *     
     */
    public void setCelllist(Celllist value) {
        this.celllist = value;
    }

    /**
     * Gets the value of the connectlist property.
     * 
     * @return
     *     possible object is
     *     {@link Connectlist }
     *     
     */
    public Connectlist getConnectlist() {
        return connectlist;
    }

    /**
     * Sets the value of the connectlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Connectlist }
     *     
     */
    public void setConnectlist(Connectlist value) {
        this.connectlist = value;
    }

    /**
     * Gets the value of the refdepends property.
     * 
     * @return
     *     possible object is
     *     {@link Refdepends }
     *     
     */
    public Refdepends getRefdepends() {
        return refdepends;
    }

    /**
     * Sets the value of the refdepends property.
     * 
     * @param value
     *     allowed object is
     *     {@link Refdepends }
     *     
     */
    public void setRefdepends(Refdepends value) {
        this.refdepends = value;
    }

    /**
     * Gets the value of the refdependLoseIDs property.
     * 
     * @return
     *     possible object is
     *     {@link RefdependLoseIDs }
     *     
     */
    public RefdependLoseIDs getRefdependLoseIDs() {
        return refdependLoseIDs;
    }

    /**
     * Sets the value of the refdependLoseIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefdependLoseIDs }
     *     
     */
    public void setRefdependLoseIDs(RefdependLoseIDs value) {
        this.refdependLoseIDs = value;
    }

    /**
     * Gets the value of the cellRemoveLog property.
     * 
     * @return
     *     possible object is
     *     {@link CellRemoveLog }
     *     
     */
    public CellRemoveLog getCellRemoveLog() {
        return cellRemoveLog;
    }

    /**
     * Sets the value of the cellRemoveLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link CellRemoveLog }
     *     
     */
    public void setCellRemoveLog(CellRemoveLog value) {
        this.cellRemoveLog = value;
    }

    /**
     * Gets the value of the rulers property.
     * 
     * @return
     *     possible object is
     *     {@link Rulers }
     *     
     */
    public Rulers getRulers() {
        return rulers;
    }

    /**
     * Sets the value of the rulers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rulers }
     *     
     */
    public void setRulers(Rulers value) {
        this.rulers = value;
    }

    /**
     * Gets the value of the conRouterType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConRouterType() {
        return conRouterType;
    }

    /**
     * Sets the value of the conRouterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConRouterType(String value) {
        this.conRouterType = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateTime(String value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the fromSourceBmf property.
     * 
     */
    public boolean isFromSourceBmf() {
        return fromSourceBmf;
    }

    /**
     * Sets the value of the fromSourceBmf property.
     * 
     */
    public void setFromSourceBmf(boolean value) {
        this.fromSourceBmf = value;
    }

    /**
     * Gets the value of the gencodestyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGencodestyle() {
        return gencodestyle;
    }

    /**
     * Sets the value of the gencodestyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGencodestyle(String value) {
        this.gencodestyle = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isbizmodel property.
     * 
     */
    public boolean isIsbizmodel() {
        return isbizmodel;
    }

    /**
     * Sets the value of the isbizmodel property.
     * 
     */
    public void setIsbizmodel(boolean value) {
        this.isbizmodel = value;
    }

    /**
     * Gets the value of the mainEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainEntity() {
        return mainEntity;
    }

    /**
     * Sets the value of the mainEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainEntity(String value) {
        this.mainEntity = value;
    }

    /**
     * Gets the value of the modifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * Sets the value of the modifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifier(String value) {
        this.modifier = value;
    }

    /**
     * Gets the value of the modifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * Sets the value of the modifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyTime(String value) {
        this.modifyTime = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the ownModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnModule() {
        return ownModule;
    }

    /**
     * Sets the value of the ownModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnModule(String value) {
        this.ownModule = value;
    }

    /**
     * Gets the value of the preLoad property.
     * 
     */
    public boolean isPreLoad() {
        return preLoad;
    }

    /**
     * Sets the value of the preLoad property.
     * 
     */
    public void setPreLoad(boolean value) {
        this.preLoad = value;
    }

    /**
     * Gets the value of the resModuleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResModuleName() {
        return resModuleName;
    }

    /**
     * Sets the value of the resModuleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResModuleName(String value) {
        this.resModuleName = value;
    }

    /**
     * Gets the value of the resid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResid() {
        return resid;
    }

    /**
     * Sets the value of the resid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResid(String value) {
        this.resid = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the versionType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionType() {
        return versionType;
    }

    /**
     * Sets the value of the versionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionType(BigInteger value) {
        this.versionType = value;
    }

}
