//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 01:45:13 PM CST 
//


package com.yonyou.studio.mdp.inspector.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}attributelist"/>
 *         &lt;element ref="{}operationlist"/>
 *         &lt;element ref="{}busiitfs"/>
 *         &lt;element ref="{}busimaps"/>
 *         &lt;element ref="{}canzhaolist"/>
 *         &lt;element ref="{}accessor"/>
 *       &lt;/sequence>
 *       &lt;attribute name="accessorClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bizItfImpClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="componentID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="createTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="creator" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="czlist" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="displayName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="fullClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="help" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="isAuthen" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isCreateSQL" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isExtendBean" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isPrimary" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="keyAttributeId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="modInfoClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="modifier" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="modifyTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="resid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="stereoType" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="tableName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="userDefClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="versionType" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="visibility" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributelist",
    "operationlist",
    "busiitfs",
    "busimaps",
    "canzhaolist",
    "accessor"
})
@XmlRootElement(name = "entity")
public class Entity {

    @XmlElement(required = true)
    protected Attributelist attributelist;
    @XmlElement(required = true)
    protected Operationlist operationlist;
    @XmlElement(required = true)
    protected Busiitfs busiitfs;
    @XmlElement(required = true)
    protected Busimaps busimaps;
    @XmlElement(required = true)
    protected Canzhaolist canzhaolist;
    @XmlElement(required = true)
    protected Accessor accessor;
    @XmlAttribute(name = "accessorClassName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String accessorClassName;
    @XmlAttribute(name = "bizItfImpClassName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bizItfImpClassName;
    @XmlAttribute(name = "componentID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String componentID;
    @XmlAttribute(name = "createTime", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String createTime;
    @XmlAttribute(name = "creator", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String creator;
    @XmlAttribute(name = "czlist", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String czlist;
    @XmlAttribute(name = "description", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String description;
    @XmlAttribute(name = "displayName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String displayName;
    @XmlAttribute(name = "fullClassName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fullClassName;
    @XmlAttribute(name = "height", required = true)
    protected BigInteger height;
    @XmlAttribute(name = "help", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String help;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "isAuthen", required = true)
    protected boolean isAuthen;
    @XmlAttribute(name = "isCreateSQL", required = true)
    protected boolean isCreateSQL;
    @XmlAttribute(name = "isExtendBean", required = true)
    protected boolean isExtendBean;
    @XmlAttribute(name = "isPrimary", required = true)
    protected boolean isPrimary;
    @XmlAttribute(name = "keyAttributeId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String keyAttributeId;
    @XmlAttribute(name = "modInfoClassName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String modInfoClassName;
    @XmlAttribute(name = "modifier", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String modifier;
    @XmlAttribute(name = "modifyTime", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String modifyTime;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "resid", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String resid;
    @XmlAttribute(name = "stereoType", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String stereoType;
    @XmlAttribute(name = "tableName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tableName;
    @XmlAttribute(name = "userDefClassName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String userDefClassName;
    @XmlAttribute(name = "versionType", required = true)
    protected BigInteger versionType;
    @XmlAttribute(name = "visibility", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String visibility;
    @XmlAttribute(name = "width", required = true)
    protected BigInteger width;
    @XmlAttribute(name = "x", required = true)
    protected BigInteger x;
    @XmlAttribute(name = "y", required = true)
    protected BigInteger y;

    /**
     * Gets the value of the attributelist property.
     * 
     * @return
     *     possible object is
     *     {@link Attributelist }
     *     
     */
    public Attributelist getAttributelist() {
        return attributelist;
    }

    /**
     * Sets the value of the attributelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attributelist }
     *     
     */
    public void setAttributelist(Attributelist value) {
        this.attributelist = value;
    }

    /**
     * Gets the value of the operationlist property.
     * 
     * @return
     *     possible object is
     *     {@link Operationlist }
     *     
     */
    public Operationlist getOperationlist() {
        return operationlist;
    }

    /**
     * Sets the value of the operationlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operationlist }
     *     
     */
    public void setOperationlist(Operationlist value) {
        this.operationlist = value;
    }

    /**
     * Gets the value of the busiitfs property.
     * 
     * @return
     *     possible object is
     *     {@link Busiitfs }
     *     
     */
    public Busiitfs getBusiitfs() {
        return busiitfs;
    }

    /**
     * Sets the value of the busiitfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Busiitfs }
     *     
     */
    public void setBusiitfs(Busiitfs value) {
        this.busiitfs = value;
    }

    /**
     * Gets the value of the busimaps property.
     * 
     * @return
     *     possible object is
     *     {@link Busimaps }
     *     
     */
    public Busimaps getBusimaps() {
        return busimaps;
    }

    /**
     * Sets the value of the busimaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Busimaps }
     *     
     */
    public void setBusimaps(Busimaps value) {
        this.busimaps = value;
    }

    /**
     * Gets the value of the canzhaolist property.
     * 
     * @return
     *     possible object is
     *     {@link Canzhaolist }
     *     
     */
    public Canzhaolist getCanzhaolist() {
        return canzhaolist;
    }

    /**
     * Sets the value of the canzhaolist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Canzhaolist }
     *     
     */
    public void setCanzhaolist(Canzhaolist value) {
        this.canzhaolist = value;
    }

    /**
     * Gets the value of the accessor property.
     * 
     * @return
     *     possible object is
     *     {@link Accessor }
     *     
     */
    public Accessor getAccessor() {
        return accessor;
    }

    /**
     * Sets the value of the accessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accessor }
     *     
     */
    public void setAccessor(Accessor value) {
        this.accessor = value;
    }

    /**
     * Gets the value of the accessorClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessorClassName() {
        return accessorClassName;
    }

    /**
     * Sets the value of the accessorClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessorClassName(String value) {
        this.accessorClassName = value;
    }

    /**
     * Gets the value of the bizItfImpClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBizItfImpClassName() {
        return bizItfImpClassName;
    }

    /**
     * Sets the value of the bizItfImpClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBizItfImpClassName(String value) {
        this.bizItfImpClassName = value;
    }

    /**
     * Gets the value of the componentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentID() {
        return componentID;
    }

    /**
     * Sets the value of the componentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentID(String value) {
        this.componentID = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateTime(String value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the czlist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCzlist() {
        return czlist;
    }

    /**
     * Sets the value of the czlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCzlist(String value) {
        this.czlist = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the fullClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullClassName() {
        return fullClassName;
    }

    /**
     * Sets the value of the fullClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullClassName(String value) {
        this.fullClassName = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isAuthen property.
     * 
     */
    public boolean isIsAuthen() {
        return isAuthen;
    }

    /**
     * Sets the value of the isAuthen property.
     * 
     */
    public void setIsAuthen(boolean value) {
        this.isAuthen = value;
    }

    /**
     * Gets the value of the isCreateSQL property.
     * 
     */
    public boolean isIsCreateSQL() {
        return isCreateSQL;
    }

    /**
     * Sets the value of the isCreateSQL property.
     * 
     */
    public void setIsCreateSQL(boolean value) {
        this.isCreateSQL = value;
    }

    /**
     * Gets the value of the isExtendBean property.
     * 
     */
    public boolean isIsExtendBean() {
        return isExtendBean;
    }

    /**
     * Sets the value of the isExtendBean property.
     * 
     */
    public void setIsExtendBean(boolean value) {
        this.isExtendBean = value;
    }

    /**
     * Gets the value of the isPrimary property.
     * 
     */
    public boolean isIsPrimary() {
        return isPrimary;
    }

    /**
     * Sets the value of the isPrimary property.
     * 
     */
    public void setIsPrimary(boolean value) {
        this.isPrimary = value;
    }

    /**
     * Gets the value of the keyAttributeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyAttributeId() {
        return keyAttributeId;
    }

    /**
     * Sets the value of the keyAttributeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyAttributeId(String value) {
        this.keyAttributeId = value;
    }

    /**
     * Gets the value of the modInfoClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModInfoClassName() {
        return modInfoClassName;
    }

    /**
     * Sets the value of the modInfoClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModInfoClassName(String value) {
        this.modInfoClassName = value;
    }

    /**
     * Gets the value of the modifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * Sets the value of the modifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifier(String value) {
        this.modifier = value;
    }

    /**
     * Gets the value of the modifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * Sets the value of the modifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyTime(String value) {
        this.modifyTime = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the resid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResid() {
        return resid;
    }

    /**
     * Sets the value of the resid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResid(String value) {
        this.resid = value;
    }

    /**
     * Gets the value of the stereoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStereoType() {
        return stereoType;
    }

    /**
     * Sets the value of the stereoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStereoType(String value) {
        this.stereoType = value;
    }

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableName(String value) {
        this.tableName = value;
    }

    /**
     * Gets the value of the userDefClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefClassName() {
        return userDefClassName;
    }

    /**
     * Sets the value of the userDefClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefClassName(String value) {
        this.userDefClassName = value;
    }

    /**
     * Gets the value of the versionType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionType() {
        return versionType;
    }

    /**
     * Sets the value of the versionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionType(BigInteger value) {
        this.versionType = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibility(String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setX(BigInteger value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setY(BigInteger value) {
        this.y = value;
    }

}
