//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 01:45:13 PM CST 
//


package com.yonyou.studio.mdp.inspector.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.yonyou.studio.mdp.inspector.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Itfid_QNAME = new QName("", "itfid");
    private final static QName _Points_QNAME = new QName("", "points");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.yonyou.studio.mdp.inspector.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Opinterface }
     * 
     */
    public Opinterface createOpinterface() {
        return new Opinterface();
    }

    /**
     * Create an instance of {@link Operationlist }
     * 
     */
    public Operationlist createOperationlist() {
        return new Operationlist();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link Paramlist }
     * 
     */
    public Paramlist createParamlist() {
        return new Paramlist();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link OpImpllist }
     * 
     */
    public OpImpllist createOpImpllist() {
        return new OpImpllist();
    }

    /**
     * Create an instance of {@link GuideList }
     * 
     */
    public GuideList createGuideList() {
        return new GuideList();
    }

    /**
     * Create an instance of {@link Rulers }
     * 
     */
    public Rulers createRulers() {
        return new Rulers();
    }

    /**
     * Create an instance of {@link Ruler }
     * 
     */
    public Ruler createRuler() {
        return new Ruler();
    }

    /**
     * Create an instance of {@link Refdepends }
     * 
     */
    public Refdepends createRefdepends() {
        return new Refdepends();
    }

    /**
     * Create an instance of {@link Dependfile }
     * 
     */
    public Dependfile createDependfile() {
        return new Dependfile();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Attributelist }
     * 
     */
    public Attributelist createAttributelist() {
        return new Attributelist();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Busiitfs }
     * 
     */
    public Busiitfs createBusiitfs() {
        return new Busiitfs();
    }

    /**
     * Create an instance of {@link Busimaps }
     * 
     */
    public Busimaps createBusimaps() {
        return new Busimaps();
    }

    /**
     * Create an instance of {@link Busimap }
     * 
     */
    public Busimap createBusimap() {
        return new Busimap();
    }

    /**
     * Create an instance of {@link Canzhaolist }
     * 
     */
    public Canzhaolist createCanzhaolist() {
        return new Canzhaolist();
    }

    /**
     * Create an instance of {@link Canzhao }
     * 
     */
    public Canzhao createCanzhao() {
        return new Canzhao();
    }

    /**
     * Create an instance of {@link Accessor }
     * 
     */
    public Accessor createAccessor() {
        return new Accessor();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Enumitemlist }
     * 
     */
    public Enumitemlist createEnumitemlist() {
        return new Enumitemlist();
    }

    /**
     * Create an instance of {@link Enumitem }
     * 
     */
    public Enumitem createEnumitem() {
        return new Enumitem();
    }

    /**
     * Create an instance of {@link Celllist }
     * 
     */
    public Celllist createCelllist() {
        return new Celllist();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Enumerate }
     * 
     */
    public Enumerate createEnumerate() {
        return new Enumerate();
    }

    /**
     * Create an instance of {@link Busioperation }
     * 
     */
    public Busioperation createBusioperation() {
        return new Busioperation();
    }

    /**
     * Create an instance of {@link Refoperationlist }
     * 
     */
    public Refoperationlist createRefoperationlist() {
        return new Refoperationlist();
    }

    /**
     * Create an instance of {@link Refoperation }
     * 
     */
    public Refoperation createRefoperation() {
        return new Refoperation();
    }

    /**
     * Create an instance of {@link Connectlist }
     * 
     */
    public Connectlist createConnectlist() {
        return new Connectlist();
    }

    /**
     * Create an instance of {@link DependConnection }
     * 
     */
    public DependConnection createDependConnection() {
        return new DependConnection();
    }

    /**
     * Create an instance of {@link Busiitfconnection }
     * 
     */
    public Busiitfconnection createBusiitfconnection() {
        return new Busiitfconnection();
    }

    /**
     * Create an instance of {@link Points }
     * 
     */
    public Points createPoints() {
        return new Points();
    }

    /**
     * Create an instance of {@link AggregationRelation }
     * 
     */
    public AggregationRelation createAggregationRelation() {
        return new AggregationRelation();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link RefdependLoseIDs }
     * 
     */
    public RefdependLoseIDs createRefdependLoseIDs() {
        return new RefdependLoseIDs();
    }

    /**
     * Create an instance of {@link CellRemoveLog }
     * 
     */
    public CellRemoveLog createCellRemoveLog() {
        return new CellRemoveLog();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "itfid")
    public JAXBElement<String> createItfid(String value) {
        return new JAXBElement<String>(_Itfid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Points }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "points")
    public JAXBElement<Points> createPoints(Points value) {
        return new JAXBElement<Points>(_Points_QNAME, Points.class, null, value);
    }

}
