//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 01:45:13 PM CST 
//


package com.yonyou.studio.mdp.inspector.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}paramlist"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dataTypeStyle" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="defclassname" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="displayName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="forBusinessEntity" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="help" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="isAggVOReturn" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isBusiActivity" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="methodException" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="opItfID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ownerElementID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="transKind" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="versionType" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="visibility" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paramlist"
})
@XmlRootElement(name = "operation")
public class Operation {

    @XmlElement(required = true)
    protected Paramlist paramlist;
    @XmlAttribute(name = "dataTypeStyle", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dataTypeStyle;
    @XmlAttribute(name = "defclassname", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String defclassname;
    @XmlAttribute(name = "displayName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String displayName;
    @XmlAttribute(name = "forBusinessEntity", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String forBusinessEntity;
    @XmlAttribute(name = "help", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String help;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "isAggVOReturn", required = true)
    protected boolean isAggVOReturn;
    @XmlAttribute(name = "isBusiActivity", required = true)
    protected boolean isBusiActivity;
    @XmlAttribute(name = "methodException", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String methodException;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "opItfID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String opItfID;
    @XmlAttribute(name = "ownerElementID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ownerElementID;
    @XmlAttribute(name = "transKind", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String transKind;
    @XmlAttribute(name = "versionType", required = true)
    protected BigInteger versionType;
    @XmlAttribute(name = "visibility", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String visibility;

    /**
     * Gets the value of the paramlist property.
     * 
     * @return
     *     possible object is
     *     {@link Paramlist }
     *     
     */
    public Paramlist getParamlist() {
        return paramlist;
    }

    /**
     * Sets the value of the paramlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paramlist }
     *     
     */
    public void setParamlist(Paramlist value) {
        this.paramlist = value;
    }

    /**
     * Gets the value of the dataTypeStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataTypeStyle() {
        return dataTypeStyle;
    }

    /**
     * Sets the value of the dataTypeStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataTypeStyle(String value) {
        this.dataTypeStyle = value;
    }

    /**
     * Gets the value of the defclassname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefclassname() {
        return defclassname;
    }

    /**
     * Sets the value of the defclassname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefclassname(String value) {
        this.defclassname = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the forBusinessEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForBusinessEntity() {
        return forBusinessEntity;
    }

    /**
     * Sets the value of the forBusinessEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForBusinessEntity(String value) {
        this.forBusinessEntity = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isAggVOReturn property.
     * 
     */
    public boolean isIsAggVOReturn() {
        return isAggVOReturn;
    }

    /**
     * Sets the value of the isAggVOReturn property.
     * 
     */
    public void setIsAggVOReturn(boolean value) {
        this.isAggVOReturn = value;
    }

    /**
     * Gets the value of the isBusiActivity property.
     * 
     */
    public boolean isIsBusiActivity() {
        return isBusiActivity;
    }

    /**
     * Sets the value of the isBusiActivity property.
     * 
     */
    public void setIsBusiActivity(boolean value) {
        this.isBusiActivity = value;
    }

    /**
     * Gets the value of the methodException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodException() {
        return methodException;
    }

    /**
     * Sets the value of the methodException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodException(String value) {
        this.methodException = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the opItfID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpItfID() {
        return opItfID;
    }

    /**
     * Sets the value of the opItfID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpItfID(String value) {
        this.opItfID = value;
    }

    /**
     * Gets the value of the ownerElementID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerElementID() {
        return ownerElementID;
    }

    /**
     * Sets the value of the ownerElementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerElementID(String value) {
        this.ownerElementID = value;
    }

    /**
     * Gets the value of the transKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransKind() {
        return transKind;
    }

    /**
     * Sets the value of the transKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransKind(String value) {
        this.transKind = value;
    }

    /**
     * Gets the value of the versionType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionType() {
        return versionType;
    }

    /**
     * Sets the value of the versionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionType(BigInteger value) {
        this.versionType = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibility(String value) {
        this.visibility = value;
    }

}
