//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 01:45:13 PM CST 
//


package com.yonyou.studio.mdp.inspector.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="industry" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isAuthorization" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isSource" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="opItfID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ownerElementID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="versiontype" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "refoperation")
public class Refoperation {

    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "industry", required = true)
    protected BigInteger industry;
    @XmlAttribute(name = "isAuthorization", required = true)
    protected boolean isAuthorization;
    @XmlAttribute(name = "isSource", required = true)
    protected boolean isSource;
    @XmlAttribute(name = "opItfID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String opItfID;
    @XmlAttribute(name = "ownerElementID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ownerElementID;
    @XmlAttribute(name = "versiontype", required = true)
    protected BigInteger versiontype;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the industry property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndustry() {
        return industry;
    }

    /**
     * Sets the value of the industry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndustry(BigInteger value) {
        this.industry = value;
    }

    /**
     * Gets the value of the isAuthorization property.
     * 
     */
    public boolean isIsAuthorization() {
        return isAuthorization;
    }

    /**
     * Sets the value of the isAuthorization property.
     * 
     */
    public void setIsAuthorization(boolean value) {
        this.isAuthorization = value;
    }

    /**
     * Gets the value of the isSource property.
     * 
     */
    public boolean isIsSource() {
        return isSource;
    }

    /**
     * Sets the value of the isSource property.
     * 
     */
    public void setIsSource(boolean value) {
        this.isSource = value;
    }

    /**
     * Gets the value of the opItfID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpItfID() {
        return opItfID;
    }

    /**
     * Sets the value of the opItfID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpItfID(String value) {
        this.opItfID = value;
    }

    /**
     * Gets the value of the ownerElementID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerElementID() {
        return ownerElementID;
    }

    /**
     * Sets the value of the ownerElementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerElementID(String value) {
        this.ownerElementID = value;
    }

    /**
     * Gets the value of the versiontype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersiontype() {
        return versiontype;
    }

    /**
     * Sets the value of the versiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersiontype(BigInteger value) {
        this.versiontype = value;
    }

}
